spring:
  profiles:
    active: dev
  application:
    name: board-service
server:
  port: 8088
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    mongodb:
      host: mongodb-test
      port: 27017
      database: admin
      username: admin
      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


